/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Productos.ControladorMovimientoProducto;
import Productos.rowProductos;
import java.awt.Dimension;
import javax.swing.Box;
import javax.swing.BoxLayout;
import Productos.ControladorProducto;
import Productos.Movimiento;
import Productos.Producto;
import Productos.rowMovimiento;
import Util.Respuesta;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.List;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.swing.Timer;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
/**
 *
 * @author Leonardo Loor <leonardoloor1988@gmail.com>
 */
public class GestionMovimientos extends javax.swing.JFrame {

    private JPopupMenu popupMenu;
    private Timer timer;
    private Movimiento movimiento = new Movimiento();
    private Producto producto_seleccionado = new Producto();
    ControladorProducto controladorproducto = new ControladorProducto();
    ControladorMovimientoProducto controladormovimiento = new ControladorMovimientoProducto();
    /**
     * Creates new form GestionProductos
     */

    public GestionMovimientos() {
        initComponents();
        
        popupMenu = new JPopupMenu();
        controladorproducto = new ControladorProducto();

        timer = new Timer(300, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                buscarProductos();
            }
        });
        timer.setRepeats(false);
        
      campo_busqueda.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) { reiniciarTimer(); }
            public void removeUpdate(DocumentEvent e) { reiniciarTimer(); }
            public void insertUpdate(DocumentEvent e) { reiniciarTimer(); }
        });
      campo_busqueda.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_DOWN && popupMenu.isVisible()) {
                    popupMenu.getComponent(0).requestFocusInWindow();
                }
            }
        });
      
      renderizarMovimientos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnActualizar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        campo_stock_producto = new javax.swing.JLabel();
        campo_busqueda = new javax.swing.JTextField();
        campo_cantidad = new javax.swing.JSpinner();
        campo_tipo = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jp_contenido = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        campo_totalIngreso = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campo_totalEgreso = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        campo_stockActual = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de Productos");
        setAlwaysOnTop(true);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pack_update_32.png"))); // NOI18N
        btnActualizar.setToolTipText("Actualizar Lista");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pack_cantidad_32.png"))); // NOI18N
        jLabel2.setToolTipText("-> Stock Disponible");

        campo_stock_producto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        campo_stock_producto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        campo_stock_producto.setText("00");
        campo_stock_producto.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        campo_busqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campo_busquedaKeyReleased(evt);
            }
        });

        campo_cantidad.setToolTipText("Cantidad a Registrar");

        campo_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INGRESO", "EGRESO" }));
        campo_tipo.setToolTipText("Tipo de transacción");

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pack_save_32.png"))); // NOI18N
        btnAgregar.setToolTipText("Guardar Movimiento");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pack_look_32.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_stock_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(campo_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campo_stock_producto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campo_busqueda)
                    .addComponent(campo_tipo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campo_cantidad, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 960, 60));

        jScrollPane1.setAlignmentX(0.0F);
        jScrollPane1.setAlignmentY(0.0F);

        jp_contenido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jp_contenido.setAlignmentY(0.0F);
        jp_contenido.setLayout(new javax.swing.BoxLayout(jp_contenido, javax.swing.BoxLayout.PAGE_AXIS));
        jScrollPane1.setViewportView(jp_contenido);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 73, 960, 410));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        campo_totalIngreso.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        campo_totalIngreso.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        campo_totalIngreso.setText("000");
        campo_totalIngreso.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Total Ingreso:");

        campo_totalEgreso.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        campo_totalEgreso.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        campo_totalEgreso.setText("000");
        campo_totalEgreso.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Total Egreso:");

        campo_stockActual.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        campo_stockActual.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        campo_stockActual.setText("000");
        campo_stockActual.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Stock Actual:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(334, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_totalIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_totalEgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_stockActual, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campo_stockActual, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campo_totalEgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campo_totalIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 496, 960, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        System.out.println("Producto:"+producto_seleccionado.getNombre());
        System.out.println("Codigo:"+producto_seleccionado.getCodigo());
        System.out.println("Cantidad a Ingresar:"+campo_cantidad.getValue());
        System.out.println("Tipo de transaccion:"+campo_tipo.getModel().getSelectedItem());    
        String mensaje = "Desea realizar el "+campo_tipo.getModel().getSelectedItem()+" de "+campo_cantidad.getValue()+" cantidades de "+producto_seleccionado.getNombre();
        int r = JOptionPane.showConfirmDialog(this,mensaje,"titulo",JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(r==0){            
            Respuesta respuesta = new Respuesta();
            int cantidad = Integer.parseInt(campo_cantidad.getValue()+"");
            String tipo = campo_tipo.getModel().getSelectedItem()+"";
            respuesta = controladormovimiento.guardarMovimiento(producto_seleccionado,cantidad,tipo);
            renderizarMovimientos();
            limpiarCampos();
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        limpiarCampos();
        renderizarMovimientos();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void campo_busquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_busquedaKeyReleased
        
    }//GEN-LAST:event_campo_busquedaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionMovimientos().setVisible(true);
            }
        });
    }
 
   private void reiniciarTimer() {
        timer.stop();
        timer.start();
    }

    private void buscarProductos() {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                String buscar = campo_busqueda.getText().trim();
                ArrayList productos = controladorproducto.getListaProductosFiltrado(buscar);
                actualizarPopupMenu(productos);
            }
        });
    }

    private void actualizarPopupMenu(ArrayList productos) {
        popupMenu.removeAll();
        if (!productos.isEmpty()) {
            for (int i = 0; i < productos.size(); i++) {
                final Producto producto = (Producto) productos.get(i);
                JMenuItem menuItem = new JMenuItem(producto.getNombre());
                menuItem.addActionListener(new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        seleccionarProducto(producto);
                    }
                });
                popupMenu.add(menuItem);
            }
            popupMenu.show(campo_busqueda, 0, campo_busqueda.getHeight());
        } else {
            popupMenu.setVisible(false);
        }
    }

    private void seleccionarProducto(Producto producto) {
        producto_seleccionado = producto;
        campo_busqueda.setText(producto_seleccionado.getNombre());
        campo_stock_producto.setText(String.valueOf(producto_seleccionado.getStock()));
        popupMenu.setVisible(false);
    }
    
    public void renderizarMovimientos() {
    jp_contenido.removeAll(); // Limpiamos todos los componentes

    ArrayList<Movimiento> listaMovimientos = controladormovimiento.getListaMovimiento(); // Obtiene la lista de los productos

    // Recorre la lista de productos
    for (Movimiento objetoMovimiento : listaMovimientos) {
        rowMovimiento rp = new rowMovimiento(objetoMovimiento); // Crear una fila de producto
        jp_contenido.add(rp); // Agrega cada producto al jp_contenido
    }

    // Ajusta y vuelve a pintar para mostrar los agregados
    jp_contenido.revalidate();
    jp_contenido.repaint();
}
    
    void limpiarCampos(){
        campo_busqueda.setText("");
        campo_cantidad.setValue(0);
        campo_stock_producto.setText("00");
        campo_tipo.setSelectedIndex(0);        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JTextField campo_busqueda;
    private javax.swing.JSpinner campo_cantidad;
    private javax.swing.JLabel campo_stockActual;
    private javax.swing.JLabel campo_stock_producto;
    private javax.swing.JComboBox<String> campo_tipo;
    private javax.swing.JLabel campo_totalEgreso;
    private javax.swing.JLabel campo_totalIngreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jp_contenido;
    // End of variables declaration//GEN-END:variables
}
