/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

/**
 *
 * @author Usuario
 */

import Conexion.Conexion;
import Productos.ControladorProducto;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.*;
import java.util.Locale;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import UI.GestionProductos;
import java.awt.BorderLayout;
import java.awt.Dimension;

public class MenuPrincipal extends javax.swing.JFrame {
    GestionProductos ventanaProductos = new GestionProductos();
    GestionMovimientos ventanaMovimientos = new GestionMovimientos();
    ControladorProducto controladorproducto = new ControladorProducto();
    Fondo fondo = new Fondo();

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {                
     
        //this.setContentPane(fondo);
        initComponents();
        
     
        
        setTitle("Sistema de Inventario");
       // setSize(1000, 700);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       // setLocationRelativeTo(null);
        
        jtb_accesorapido.setVisible(true);
              
        
        
        this.add(jtb_accesorapido);
        
        Conexion con= new Conexion();
        con.establecerConexion();        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtb_accesorapido = new javax.swing.JToolBar();
        btnProducto = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnMovimientos = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmi_productos = new javax.swing.JMenuItem();
        jmi_movimientos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmi_usuarios = new javax.swing.JMenuItem();
        jmi_salir = new javax.swing.JMenuItem();
        jmi_reporte_movimiento = new javax.swing.JMenu();
        jmi_reporte_movimientos = new javax.swing.JMenuItem();
        jmi_listaproductos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Programa de Inventarios");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jtb_accesorapido.setRollover(true);
        jtb_accesorapido.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jtb_accesorapido.setMinimumSize(new java.awt.Dimension(126, 64));
        jtb_accesorapido.setPreferredSize(new java.awt.Dimension(155, 40));

        btnProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pack_check_32.png"))); // NOI18N
        btnProducto.setToolTipText("Gestionar Productos");
        btnProducto.setFocusable(false);
        btnProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProducto.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnProducto.setMaximumSize(new java.awt.Dimension(45, 45));
        btnProducto.setMinimumSize(new java.awt.Dimension(45, 45));
        btnProducto.setPreferredSize(new java.awt.Dimension(45, 45));
        btnProducto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoActionPerformed(evt);
            }
        });
        jtb_accesorapido.add(btnProducto);
        jtb_accesorapido.add(jSeparator2);

        btnMovimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pack_movimiento_32.png"))); // NOI18N
        btnMovimientos.setToolTipText("Gestionar Movimientos");
        btnMovimientos.setFocusable(false);
        btnMovimientos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMovimientos.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnMovimientos.setMaximumSize(new java.awt.Dimension(45, 45));
        btnMovimientos.setMinimumSize(new java.awt.Dimension(45, 45));
        btnMovimientos.setPreferredSize(new java.awt.Dimension(45, 45));
        btnMovimientos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovimientosActionPerformed(evt);
            }
        });
        jtb_accesorapido.add(btnMovimientos);

        jMenu1.setText("Archivo");

        jmi_productos.setText("Gestionar Productos");
        jmi_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_productosActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_productos);

        jmi_movimientos.setText("Gestionar Movimientos");
        jmi_movimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_movimientosActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_movimientos);
        jMenu1.add(jSeparator1);

        jmi_usuarios.setText("Usuarios");
        jmi_usuarios.setEnabled(false);
        jmi_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_usuariosActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_usuarios);

        jmi_salir.setText("Salir");
        jmi_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_salirActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_salir);

        jMenuBar1.add(jMenu1);

        jmi_reporte_movimiento.setText("Reportes");

        jmi_reporte_movimientos.setText("Movimientos");
        jmi_reporte_movimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_reporte_movimientosActionPerformed(evt);
            }
        });
        jmi_reporte_movimiento.add(jmi_reporte_movimientos);

        jmi_listaproductos.setText("Lista Productos");
        jmi_listaproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_listaproductosActionPerformed(evt);
            }
        });
        jmi_reporte_movimiento.add(jmi_listaproductos);

        jMenuBar1.add(jmi_reporte_movimiento);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtb_accesorapido, javax.swing.GroupLayout.DEFAULT_SIZE, 974, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtb_accesorapido, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 394, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_productosActionPerformed
        //llamar a panel de productos
        ventanaProductos.setLocationRelativeTo(null);
        ventanaProductos.setVisible(true);
    }//GEN-LAST:event_jmi_productosActionPerformed

    private void jmi_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_usuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_usuariosActionPerformed

    private void jmi_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jmi_salirActionPerformed

    private void jmi_reporte_movimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_reporte_movimientosActionPerformed
        
    }//GEN-LAST:event_jmi_reporte_movimientosActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        Dimension dm = new Dimension(this.getWidth(),56);
        jtb_accesorapido.setSize(dm);
        jtb_accesorapido.setPreferredSize(dm);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_formComponentResized

    private void btnProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoActionPerformed
       jmi_productos.doClick();
    }//GEN-LAST:event_btnProductoActionPerformed

    private void jmi_movimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_movimientosActionPerformed
       ventanaMovimientos.setLocationRelativeTo(null);
       ventanaMovimientos.setVisible(true);
    }//GEN-LAST:event_jmi_movimientosActionPerformed

    private void btnMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovimientosActionPerformed
        jmi_movimientos.doClick();
    }//GEN-LAST:event_btnMovimientosActionPerformed

    private void jmi_listaproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_listaproductosActionPerformed
       JasperPrint jp = controladorproducto.reporteTodosProductos();
        //JasperViewer.viewReport(jp);
        JasperViewer.viewReport(jp, false, Locale.ENGLISH);
    }//GEN-LAST:event_jmi_listaproductosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMovimientos;
    private javax.swing.JButton btnProducto;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JMenuItem jmi_listaproductos;
    private javax.swing.JMenuItem jmi_movimientos;
    private javax.swing.JMenuItem jmi_productos;
    private javax.swing.JMenu jmi_reporte_movimiento;
    private javax.swing.JMenuItem jmi_reporte_movimientos;
    private javax.swing.JMenuItem jmi_salir;
    private javax.swing.JMenuItem jmi_usuarios;
    private javax.swing.JToolBar jtb_accesorapido;
    // End of variables declaration//GEN-END:variables

    class Fondo extends JPanel{
        private Image imagen;
        
        @Override
        public void paint(Graphics g){
            //imagen = new ImageIcon(getClass().getResource("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\SistemaMatricula\\src\\main\\java\\com\\mycompany\\sistemamatricula\\Imagenes\\Inicio.png")).getImage();
            imagen = new ImageIcon("C:\\MAESTRIA\\MODULO 4 - Plataformas de desarrollo de software\\TAREA 1\\inventario_java\\sistemaInventario\\mavenproject1\\src\\main\\java\\Imagen\\fondo_principal.png").getImage();
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            
            super.paint(g);
        }

       
    }
    
}
